name: Build and publish release

on:
  push:
    tags:
      - 'v*.*.*.*'
  workflow_dispatch:

jobs:
  build-release:
    name: Build and release installers
    runs-on: windows-latest

    env:
      DISTRIBUTION: 'dist'
      VERSION: 'version.json'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Configure
        run: |
          git config --local user.email "${MAIL}"
          git config --local user.name "${NAME}"
        env:
          MAIL: 41898282+github-actions[bot]@users.noreply.github.com
          NAME: github-actions[bot]
        shell: bash

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup prerequisites
        run: python -m pip install --upgrade pip pipenv

      - name: Create virtual environment
        run: python -m pipenv install

      - name: Build installer binaries
        run: python -m pipenv run python main.py --version "${{ env.VERSION }}"

      - id: license
        name: Import license
        run: |
          cp "thirdparty\terminal\LICENSE" "${LICENSE}"
          echo "::set-output name=file::${LICENSE}"
        shell: bash
        env:
          LICENSE: ${{ env.DISTRIBUTION }}\LICENSE

      - id: tag
        name: Get current tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
        shell: bash

      - id: url
        name: Get official release URL
        run: echo "::set-output name=url::$(jq -r .html_url ${{ env.VERSION }})"
        shell: bash

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: >
            See the [official release notes](${{ steps.url.outputs.url }}) for
            more information about changes and fixes. This project is not
            affiliated with Microsoft Corporation in any way.
          name: Windows Terminal ${{ steps.tag.outputs.tag }}
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            ${{ env.DISTRIBUTION }}\WindowsTerminal*.exe
            ${{ steps.license.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
